# Generated by Django 2.0.2 on 2018-03-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20180222_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='foundation',
            field=models.CharField(blank=True, default='СВФ', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='roof_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
