# Generated by Django 2.0.2 on 2018-03-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
