# Generated by Django 2.0.2 on 2018-03-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='floors',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
