# Generated by Django 2.0.2 on 2018-03-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20180304_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='floors',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='roof_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
