# Generated by Django 2.0.2 on 2018-03-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_water_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='front_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
